import Head from 'next/head'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Navbar from './components/Navbar'

export const metadata = {
  title: 'We Care',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en" className='m-0'>
      <Head> <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"  rel="stylesheet" />
       </Head>

      <body className={inter.className}>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
      <Navbar/>
      



        {children}</body>
    </html>
  )
}
